### ISSUE TITLE
Design a Better UI

### ISSUE THREAD

**Issue by decoded-cipher** [decoded-cipher/colortool#9]
### **To-Do List:**

- [ ] Fork the Repository
- [ ] Clone it to Local Machine
- [ ] Start designing a New User Interface
- [ ] Design as much as you can...
- [ ] Commit and Push it to your remote Repository
- [ ] Create a Pull Request towards this Main Repository

### **Things to Remember**

1. Design should not compromise the functionality of the tool
2. Design must be Device Responsive (Desktop View and Mobile View)
3. Use HTML, CSS and JavaScript
4. Use Bootstrap

### **Here is the Present View of the Page:**

**1. Desktop:**
![image](https://user-images.githubusercontent.com/44474792/113891786-09a34f00-97e3-11eb-9d1d-22812bff5343.png)
**2. Mobile View:**
![image](https://user-images.githubusercontent.com/44474792/113892526-b54c9f00-97e3-11eb-8442-19979793fc86.png)
